/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d0e27ae1-ccb5-48bd-997b-b1429824520f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_WXFDAaxQV",
    "aws_user_pools_web_client_id": "6gtsnhu9pc108ti4u34etrq9em",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://gvc6gfukybfjjglemcxpode52q.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jfaadirhnfdw7b4jgpso72ma2q",
    "aws_user_files_s3_bucket": "filesbucket163807-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
